0416/0416/ntust/Scripts/mysite/cms/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^$', views.index, name='index')
]

0416/0416/ntust/Scripts/mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^cms/', include('cms.urls')),
    url(r'^admin/', admin.site.urls),
]

0416/0416/ntust/Scripts/mysite/cms/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
	name = models.CharField(max_length=20)
	phone_number = models.CharField(max_length=15)
	address = models.CharField(max_length=50, blank = True)

	def __str__(self):
		return self.name


class ProfileIntro(models.Model):
	name = models.CharField(max_length=20) #限制最多三位元	
	sex = models.CharField(max_length=20)
	comment = models.CharField(max_length=7000, blank = True)
	profile = models.ForeignKey(Profile,on_delete=models.DO_NOTHING)

	def __str__(self):
		return self.name

#python manage.py makemigrations cms
#python manage.py migrate

0416/0416/ntust/Scripts/mysite/cms/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponse
# Create your views here.

from .models import Profile, ProfileIntro

def index(request):
	profiles = Profile.objects.all()
	return render_to_response('cms/menu.html',locals())

0416/0416/ntust/Scripts/mysite/cms/templates/cms/menu.html
<h1>個人介紹</h1>
{% for r in profiles %}
<h2>{{ r.name }}</h2>

<table class="table">
	<tr>
		<th>姓名</th>
		<th>性別</th>
		<th>簡介</th>
	</tr>
	{% for e in r.profileintro_set.all %}
	<tr>
		<td>{{ e.name }}</td>
		<td>{{ e.sex }}</td>
		<td>{{ e.comment }}</td>
	</tr>
	{% endfor %}
</table>
	{% endfor %}	